package com.sclass.domain.domains.lesson.exception

import com.sclass.common.exception.BusinessException

class LessonNotFoundException : BusinessException(LessonErrorCode.LESSON_NOT_FOUND)

class LessonInvalidStatusTransitionException : BusinessException(LessonErrorCode.LESSON_INVALID_STATUS_TRANSITION)

class LessonNotCompletedException : BusinessException(LessonErrorCode.LESSON_NOT_COMPLETED)

class LessonAlreadyCompletedException : BusinessException(LessonErrorCode.LESSON_ALREADY_COMPLETED)

class LessonInvalidTimeException : BusinessException(LessonErrorCode.LESSON_INVALID_TIME)

class LessonAlreadyStartedException : BusinessException(LessonErrorCode.LESSON_ALREADY_STARTED)

class LessonScheduleAlreadyExistsException : BusinessException(LessonErrorCode.LESSON_SCHEDULE_ALREADY_EXISTS)

class LessonScheduleNotFoundException : BusinessException(LessonErrorCode.LESSON_SCHEDULE_NOT_FOUND)

class LessonScheduleConflictException : BusinessException(LessonErrorCode.LESSON_SCHEDULE_CONFLICT)

class LessonScheduleSyncRequiredException : BusinessException(LessonErrorCode.LESSON_SCHEDULE_SYNC_REQUIRED)
