package com.sclass.domain.domains.lesson.exception

import com.sclass.common.exception.BusinessException

class LessonNotFoundException : BusinessException(LessonErrorCode.LESSON_NOT_FOUND)

class LessonInvalidStatusTransitionException : BusinessException(LessonErrorCode.LESSON_INVALID_STATUS_TRANSITION)

class LessonNotCompletedException : BusinessException(LessonErrorCode.LESSON_NOT_COMPLETED)

class LessonAlreadyCompletedException : BusinessException(LessonErrorCode.LESSON_ALREADY_COMPLETED)
